# _config.yml

title: "Saadman Sakib"
logo: "assets/img/casual_look.png"  
description: "Lecturer, Department of CSE, Chittagong University of Engineering and Technology"
theme: jekyll-theme-minimal
show_downloads: false

